config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    validates :title, presence: true, length: { minimum: 6, maximum: 100 }
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end 

app/models/user.rb
class User <ApplicationRecord
    before_save { self.email = email.downcase}
    has_many :articles
    validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 25}
    VALID_EMAIL_REGEX = /A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: {case_sensitive: false}, length: { maximum: 105 }, format: { with: VALID_EMAIL_REGEX }
    has_secure_password
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def show
    end

    def index
        @articles = Article.paginate(page: params[:page], per_page: 2)
    end

    def new
       @article = Article.new
    end

    def edit
    end

    def create
        @article = Article.new(article_params) 
        @article.user = User.first
        if @article.save
          flash[:notice] = "Article was created succesfully."
          redirect_to @article
        else 
          render 'new'
        end
    end

    def update
      if @article.update(article_params)
        flash[:notice] = "Article was updated successfully."
      else
        render 'edit'
      end
    end

    def destroy
      @article.destroy
      redirect_to articles_path
    end

    private

    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description)
    end

    def require_same_user
      if current_user != @article.user && !current_user.admin?
        flash[:alert] = "You can only edit or delete your own article"
        redirect_to @article
      end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end

    def about
    end

end

app/controllers/users_controller.rb
class UsersController <ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:edit, :update]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def show
        @user = User.find(params[:id])
        @articles = @user.articles.paginate(page: params[:page], per_page: 2)
    end
 
    def index
        @users = User.paginate(page: params[:page], per_page: 2)
    end

    def new
        @user = User.new
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = "Your account information was successfully updated"
            redirect_to @user
        else
            render 'edit'
        end
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:notice] = "Welcome to the Agus Blog #{@user.username}, you have successfully signed up"
            redirect_to articles_path
        else 
            render 'new'
        end
    end

    def destroy
        @user.destroy
        session[:user_id] = nil if @user == current_user
        flash[:notice] = "Account and all associated articles successfully deleted"
        redirect_to articles_path
      end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def set_user
        @user = User.find(params[:id])
      end
    
      def require_same_user
        if current_user != @user && !current_user.admin?
          flash[:alert] = "You can only edit or delete your own account"
          redirect_to @user
        end
      end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, options = { size: 80})
      email_address = user.email.downcase
      hash = Digest::MD5.hexdigest(email_address)
      size = options[:size]
      gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
      image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
    end
  
  end

app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <% if article.user %>
              by <%= link_to article.user.username, user.path(article.user) %>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
            <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
            <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
            edited <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div> 

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
    <h2>The following erros prevented the article from being saved</h2>
    <ul>
        <% @article.errors.full_messages.each do |msg| %>
           <li> <%= msg %> </li>
        <%end%>
    </ul>
<% end %>

<%= form_with(model: @article, local: true) do |f| %>
    <p>
        <%= f.label :title %><br/>
        <%= f.text_field :title %>
    </p>

    <p>
        <%= f.label :description %><br/>
        <%= f.text_area :description %>
    </p>
    <p>
    <%= f.submit %>
    </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Cancel and return to articles listing', articles_path %>

app/views/articles/index.html.erb
<h1>Listing all articles<h1>

<div class="flickr_pagination"> 
    <%= will_paginate @articles, :container => false %>
</div>
<%= render 'article' %> 
<div class="flickr_pagination"> 
    <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1>Create a new article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @article.title %></h2>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          <% if @article.user %>
            by <%= @article.user.username %>
            <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
          <% end %>
        </div>
        <div class="card-body">
          <div class="card-text text-left"><%= @article.description %></div>
          <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
          <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= @article.created_at %> ago,  
          edited <%= @article.updated_at %> ago</small>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <%= msg %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Bloggers", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? %>
            <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
          <% end %>  
          <%= link_to "View articles", articles_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? && current_user.admin? %>
            <%= link_to "Create new category", new_category_path, class: "dropdown-item" %>
          <% end %>  
          <%= link_to "View categories", categories_path, class: "dropdown-item" %>
        </div>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?" } %> 
          </div>
        </li>
        <li class="nav-item">
          <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log in', login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: "nav-link" %>
        </li>
      <% end %>
      </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AgusBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to the About page</h1>

<%= link_to 'Articles listing', articles_path %> |
<%= link_to 'Home page', root_path %>

app/views/pages/home.html.erb
<h1>Welcome to the Homepage</h1>
<%= link_to 'Sign up', signup_path %> |
<%= link_to 'Articles listing', articles_path %> |
<%= link_to 'About page', about_path %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
    <h2>The following erros prevented the user from being saved</h2>
    <ul>
        <% @user.errors.full_messages.each do |msg| %>
           <li> <%= msg %> </li>
        <%end%>
    </ul>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
    <p>
        <%= f.label :username %><br/>
        <%= f.text_field :username %>
    </p>

    <p>
        <%= f.label :email %><br/>
        <%= f.email_field :email %>
    </p>

    <p>
        <%= f.label :password %><br/>
        <%= f.password_field :password %>
    </p>
    <p>
    <%= f.submit(@user.new_record? ? "Sign up" : "Update account")  %>
    </p>
<% end %>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>
<%= render 'form' %> 

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Bloggers</h1>

<div class="flickr_pagination"> 
    <%= will_paginate @users, :container => false %>
</div>
 
<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%= link_to user.username, user %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to gravatar_for(user, size: 150), user %>
            </h5>
            <%= link_to "View profile", user, class: "btn btn-outline-success" %>
            <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination"> 
    <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1>Sign up for Agus Blog</h1>
<%= render 'form' %>
<%= link_to 'Return to articles listing', articles_path %>

app/views/users/show.html.erb
<h1><%= @user.username%>'s profile</h1>

<%= gravatar_for @user, size: 200 %>

<div>
    <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
</div>
<h3 class="text-center mt-4">Articles</h3>

<%= render 'articles/article' %>

<div class="flickr_pagination"> 
    <%= will_paginate @articles, :container => false %>
</div>